# fly.toml app configuration file generated for server-long-glitter-8298 on 2024-09-29T02:25:20+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-long-glitter-8298'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
